### PR TITLE
[Deque] Work around stdlib issue with Array.withContiguousStorageIfAvailable

### LINKED ISSUE #27: Fatal error: unsupported: file Swift/ArrayBuffer.swift, line 231
When initializing a `Deque` from an `Array` (coming from `NSArray`), it crashes at runtime with error:

```
Fatal error: unsupported: file Swift/ArrayBuffer.swift, line 231
```

### Information

- **Package version:** commit 65a3841
- **Platform version:** macOS 11.2.1 (20D74)
- **Swift version:** Apple Swift version 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28)
Target: x86_64-apple-darwin20.3.0

### Checklist

- [x] If possible, I've reproduced the issue using the `main` branch of this package.
- [x] I've searched for [existing GitHub issues](https://github.com/apple/swift-collections/issues).

### Steps to Reproduce

Crashes at runtime (Deque+RangeReplaceableCollection.swift:144):
```swift
let array = NSArray(arrayLiteral: NSString()) as! [NSObject]
let deque = Deque(array)
```

Runs without crashing:
```swift
let array = NSArray(arrayLiteral: NSString()) as! [NSObject]
let deque = Deque(Array(array))
```

### Expected behavior
The first example above doesn’t crash.

### Actual behavior
Only the second example doesn’t crash.

### PR DESCRIPTION
**Pull request by lorentey**
Resolves #27 by updating `Deque.init(_:)`, `.append(contentsOf:)` and `.prepend(contentsOf:)` to not call `Array.withContiguousStorageIfAvailable` if there is a chance doing so may trigger the underlying stdlib issue.

### Checklist
- [X] I've read the [Contribution Guidelines](/README.md#contributing-to-swift-collections)
- [X] My contributions are licensed under the [Swift license](/LICENSE.txt).
- [X] I've followed the coding style of the rest of the project.
- [X] I've added tests covering all new code paths my change adds to the project (if appropriate).
- [ ] I've added benchmarks covering new functionality (if appropriate).
- [X] I've verified that my change does not break any existing tests or introduce unexplained benchmark regressions.
- [ ] I've updated the documentation if necessary.

### CODE REVIEW

File: Sources/DequeModule/Deque+Extras.swift [hunk 1]
```diff
@@ -166,6 +166,12 @@ extension Deque {
   /// - SeeAlso: `append(contentsOf:)`
   @inlinable
   public mutating func prepend<S: Sequence>(contentsOf newElements: S) where S.Element == Element {
+    let done: Void? = newElements._withContiguousStorageIfAvailable_SR14663 { source in
```
Comment (lorentey) [inline Sources/DequeModule/Deque+Extras.swift:169]: I couldn't resist slipping in this trivial performance improvement, if only for symmetry with the sequence-based `append(contentsOf:)`.

**Comment by lorentey** [comment]
@swift-ci test

File: Sources/DequeModule/Compatibility.swift [hunk 2]
```diff
@@ -0,0 +1,60 @@
...
+
+extension Sequence {
+  // An adjusted version of the standard `withContiguousStorageIfAvailable`
+  // method that works around https://bugs.swift.org/browse/SR-14663.
+  @inlinable
+  internal func _withContiguousStorageIfAvailable_SR14663<R>(
+    _ body: (UnsafeBufferPointer<Element>) throws -> R
+  ) rethrows -> R? {
+    if Self.self == Array<Element>.self && Array<Element>._isWCSIABroken() {
+      return nil
```
Comment (lorentey) [inline Sources/DequeModule/Compatibility.swift:55]: If we had a reliable/easy way to test if a particular array instance is bridged, then we could let native arrays pass through here. 🤔

**Comment by lorentey** [comment]
@swift-ci test

File: Tests/DequeTests/DequeTests.swift [hunk 3]
```diff
@@ -319,5 +320,55 @@ final class DequeTests: CollectionTestCase {
...
+              prependSequence(contentsOf: extra, to: &deque)
+              expectEqualElements(deque, contents)
+            }
+          }
+        }
+      }
+    }
+  }
+
+  func test_prependManyFromBridgedArray() {
```
Comment (stephentyrone) [inline Tests/DequeTests/DequeTests.swift:351]: Thank you for adding the additional test cases =)

**Review by stephentyrone — APPROVED** [review]

File: Sources/DequeModule/Compatibility.swift (hunk 2 above)
Comment (karwa) [reply Sources/DequeModule/Compatibility.swift:57]: Maybe:

```swift
if let array = self as? Array<Element>, array._baseAddressIfContiguous == nil { return nil }
```

Tested in a Playground:
```swift
import Foundation
var a: [NSObject] = [NSObject()]
print(a._baseAddressIfContiguous) // Optional(0x00007fdf7e40c0d0)

a = NSArray(array: [NSObject()]) as! [NSObject]
print(a._baseAddressIfContiguous) // nil
```

Comment (lorentey) [reply Sources/DequeModule/Compatibility.swift:57]: Huh, that's a good find. Looking at similarly exposed members, `Array._hoistableIsNativeTypeChecked()` might be even better.

There are (at least) two worries with using these underscored APIs: (including `_isBridgedVerbatimToObjectiveC` above)

1. Swift doesn't promise it won't change their behavior, so it's tricky to safely use them in code that is not part of the stdlib. E.g., I imagine for element types that don't require a dynamic type check at every access, we may want to change `_baseAddressIfContiguous` to return non-nil for bridged arrays that use specific known NSArray subclasses. 

2. These have also been made public for historical reasons, rather than any intentional design, and we may find a good reason to change them to `@inlinable internal`, disallowing direct calls like this in future SDKs. We wouldn't be able to remove the entry points themselves (they are part of Swift's ABI), but we might need to restrict them to only be called from inlinable functions within the stdlib.

As this package is maintained by the same people who work on the Swift stdlib, I think it's not unreasonable for this package to use these. At the first sign of trouble, we can remove the calls, or limit them to older Swift toolchains. The primary danger is that this code will spread beyond this package through vendoring or uncritical copy-n-paste. 

My instinct as a stdlib engineer tells me that the risk is low with `_hoistableIsNativeTypeChecked` (and pretty much nonexistent for `_isBridgedVerbatimToObjectiveC`); on the other hand, this package is inherently averse to even low-risk stuff. Hm.

Comment (lorentey) [reply Sources/DequeModule/Compatibility.swift:57]: I think the best thing to do is to keep this as is for now until we have a Swift release (let's call it x.y) that contains a fix for the underlying issue. In the (unlikely) case that the fix won't back deploy, then we can add a call to `_hoistableIsNativeTypeChecked` restricted to only be called on Swift 5.1 ..< x.y.

Comment (stephentyrone) [reply Sources/DequeModule/Compatibility.swift:57]: I think that's fine. I would also be OK with doing the workaround here now, so long as we put a comment in the stdlib that references this bug.
