### PR TITLE
[1.0] Backport Sendable conformances on all public types

### LINKED ISSUE #317: Ship Sendable annotations in 1.0.6
Enabling strict concurrency diagnostics is now a common thing; we cannot keep shipping swift-collections without `Sendable` conformances.

- Cherry pick https://github.com/apple/swift-collections/pull/191 onto release/1.0
- Ship it in a patch release, 1.0.6.

New conformances are usually considered API changes, and they would need to ship in a new minor release. However, `Sendable` is not a regular protocol. On reflection, making types conform to `Sendable` are not really API additions in the usual sense, like adding `Equatable` -- `Sendable` is more like a required declaration that adds proper support for Swift 5.5+ toolchains. 

Therefore, I think that adding Sendable declarations better match the risk profile of patch release than a full minor version. (They feel closer to https://github.com/apple/swift-collections/pull/268/files, than, say, a change that added a new method to an existing type.)  We have some precedent in doing this in the [1.0.2 release of swift-atomics](https://github.com/apple/swift-atomics/releases/tag/1.0.2) -- although there our hands were forced by the new compiler "helpfully" inferring incorrect Sendable conformances for us.

### PR DESCRIPTION
**Pull request by lorentey**
This backports #191 to the release/1.0 branch, retrofitting that release series with proper support for Swift 5.5.

Resolves #317

### Checklist
- [X] I've read the [Contribution Guidelines](/README.md#contributing-to-swift-collections)
- [X] My contributions are licensed under the [Swift license](/LICENSE.txt).
- [X] I've followed the coding style of the rest of the project.
- [ ] I've added tests covering all new code paths my change adds to the project (if appropriate).
- [ ] I've added benchmarks covering new functionality (if appropriate).
- [ ] I've verified that my change does not break any existing tests or introduce unexplained benchmark regressions.
- [ ] I've updated the documentation if necessary.

### CODE REVIEW

**Comment by lorentey** [comment]
@swift-ci test

**Comment by lorentey** [comment]
macOS PR tests are expected to fail. 🐶🔥

File: Sources/OrderedCollections/OrderedDictionary/OrderedDictionary+Sendable.swift [hunk 1]
```diff
@@ -0,0 +1,15 @@
+//===----------------------------------------------------------------------===//
+//
+// This source file is part of the Swift Collections open source project
+//
+// Copyright (c) 2022 Apple Inc. and the Swift project authors
```
Comment (glessard) [inline Sources/OrderedCollections/OrderedDictionary/OrderedDictionary+Sendable.swift:5]: 2022?

Comment (lorentey) [reply Sources/OrderedCollections/OrderedDictionary/OrderedDictionary+Sendable.swift:5]: Oh how time flies when we're having fun!

**Review by glessard — APPROVED** [review]

**Comment by lorentey** [comment]
@swift-ci test linux platform

**Review by glessard — APPROVED** [review]
